global using Practice;
global using static System.Math;
global using static System.Console;
global using System.Collections;
global using static Practice.Function;
global using Practice.other;
global using static Practice.other.Helper;
global using Newtonsoft.Json;
global using System.Text;
global using Complex = System.Numerics.Complex;
global using Practice.numerics;